### ISSUE TITLE
USING P4_INT

### ISSUE THREAD

**Issue by euclidesfjr** [coolvikas/P4_INT#3]
Hi, good morning, can you help me? Because in the test that I am working I can not make the system work correctly, because I do not know how to use the * .py commands below, since I can only generate send packages, receive packages do not generate when I use this program. Another thing, how to configure the size of the connection bandwidth links between networks in this scenario?

euclidesfjr@kaxassa:~/P03/P4_INT-ORIGINAL/P4_INT/INT_headerstack$ ls -lrt *.py
-rwxrwxr-x 1 euclidesfjr euclidesfjr  1035 Jan 12 17:54 original_send.py
-rwxrwxr-x 1 euclidesfjr euclidesfjr  3272 Jan 12 17:54 original_receive.py
-rw-rw-r-- 1 euclidesfjr euclidesfjr   713 Jan 12 17:54 cpu_plot.py
-rwxrwxr-x 1 euclidesfjr euclidesfjr  5202 Jan 12 17:54 receive_udp.py
-rwxrwxr-x 1 euclidesfjr euclidesfjr 12874 Jan 12 17:54 receive_udp_no_packets_h1.py
-rwxrwxr-x 1 euclidesfjr euclidesfjr 14269 Jan 12 17:54 receive_udp_multithreaded_h2.py
-rwxrwxr-x 1 euclidesfjr euclidesfjr 14661 Jan 12 17:54 receive_udp_multithreaded_h1.py
-rwxrwxr-x 1 euclidesfjr euclidesfjr  4554 Jan 12 17:54 receive_tcp.py
-rw-rw-r-- 1 euclidesfjr euclidesfjr  8052 Jan 12 17:54 receive_tcp_normaldist.py
-rwxrwxr-x 1 euclidesfjr euclidesfjr  8052 Jan 12 17:54 receive_tcp_normaldist_original.py
-rwxrwxr-x 1 euclidesfjr euclidesfjr  8282 Jan 12 17:54 receive_tcp_multithreaded.py
-rwxrwxr-x 1 euclidesfjr euclidesfjr   330 Jan 12 17:54 process_deq.py
-rw-rw-r-- 1 euclidesfjr euclidesfjr   345 Jan 12 17:54 print_packets.py
-rw-rw-r-- 1 euclidesfjr euclidesfjr  2555 Jan 12 17:54 populate_sx_xommands_file.py
-rwxrwxr-x 1 euclidesfjr euclidesfjr   391 Jan 12 17:54 tcp_single_send.py
-rwxrwxr-x 1 euclidesfjr euclidesfjr   492 Jan 12 17:54 tcp_single_receive.py
-rwxrwxr-x 1 euclidesfjr euclidesfjr  1938 Jan 12 17:54 send_udp.py
-rwxrwxr-x 1 euclidesfjr euclidesfjr  3354 Jan 12 17:54 send_udp_normaldist.py
-rwxrwxr-x 1 euclidesfjr euclidesfjr  1424 Jan 12 17:54 send_tcp.py
-rwxrwxr-x 1 euclidesfjr euclidesfjr  3370 Jan 12 17:54 send_tcp_normaldist.py
-rw-rw-r-- 1 euclidesfjr euclidesfjr   225 Jan 12 17:54 send_tcp_flows.py

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Because I can not generate * .pcap files for IN (input), only OUT (output). Can you help me? Since I can not get the network to communicate between IP addresses.

**Comment by coolvikas** [comment]
Hi @euclidesfjr, Please run the send_udp.py file on the h1 host and receive_udp.py script on the h8 host. Also please ensure that before running p4 code your hosts are able to ping each other.

**Comment by euclidesfjr** [comment]
Hi, good morning, thank you very much for your attention, but I'm not able to execute. Maybe I did not understand the program send_udp.py and the program send_tcp.py, because when running it does not work, even though I see the arguments it asks, see how I executed it.

euclidesfjr @ kaxassa: ~ / P03 / P4_INT-ORIGINAL / P4_INT / INT_headerstack $ ./send_udp.py h1
WARNING: No route found for IPv6 destination :: (no default route?)
pass 2 arguments: <destination> "<message>"
euclidesfjr @ kaxassa: ~ / P03 / P4_INT-ORIGINAL / P4_INT / INT_headerstack $
+++++++++++++++++++++++++++++++
euclidesfjr @ kaxassa: ~ / P03 / P4_INT-ORIGINAL / P4_INT / INT_headerstack $ ./send_udp.py h1 "test"
WARNING: No route found for IPv6 destination :: (no default route?)
Traceback (most recent call last):
  File "./send_udp.py", line 61, in <module>
    main ()
  File "./send_udp.py", line 32, in main
    addr = socket.gethostbyname (sys.argv [1])
socket.gaierror: [Errno -2] Name or service not known
euclidesfjr @ kaxassa: ~ / P03 / P4_INT-ORIGINAL / P4_INT / INT_headerstack $
++++++++++++++++++++++++++++++++++++++++

Okay, but how to do this ?? "Also please ensure that before running your hosts are able to ping each other."

Thanks very much for the help, I need to be able to do an article about it.
